kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.kubescapeServiceAccountName }}-roles
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "describe"{{ if .Values.kubescape.enableHostScan }}, "watch"{{ end }}]
{{ if .Values.kubescape.enableHostScan }}
# Host scan daemonset runs in dedicated namespace applied by kubescape at the begining of the scan.
# At the end of the resources collecting stage Kubescape is taking down both the namespace and the daemonset
- apiGroups: ["", "apps"]
  resources: ["namespaces", "daemonsets"]
  verbs: ["*"]
{{ end }}