kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.operatorServiceAccountName }}-role-binding
  namespace: {{ .Values.ksNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.global.operatorServiceAccountName }}-roles
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.operatorServiceAccountName }}
  namespace: {{ .Values.ksNamespace }}