kind: ConfigMap 
apiVersion: v1 
metadata:
  name: kubescape-cronjob-template
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.global.beConfig }}
    tier: {{ .Values.global.namespaceTier }}
data:
  cronjobTemplate: |-
    {{ tpl (.Files.Get "assets/armo-kubescape-cronjob-full.yaml") . }}
