{{- if .Values.armoScanScheduler.enabled  }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.armoScanScheduler.name }}-config
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoScanScheduler.name }}
    tier: {{ .Values.global.namespaceTier }}
data:
  trigger-script.sh: |-
    #!/bin/sh
    curl -X POST http://{{ .Values.armoWebsocket.name }}:{{ .Values.armoWebsocket.service.port }}/v1/triggerAction -H 'Content-Type: application/json' -d '{"commands":[{"CommandName": "scan", "WildWlid": "wlid://cluster-{{ regexReplaceAll "\\W+" .Values.clusterName "-" | lower  }}"}]}'
{{- end }}
