{{- if .Values.createKubescapeServiceAccount -}}
{{- $cloud_provider := (include "cloud_provider" .) -}}
kind: ServiceAccount
apiVersion: v1
metadata:
{{- if .Values.aws_iam_role_arn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws_iam_role_arn }}
  {{- else if .Values.gke_service_account }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gke_service_account }}
{{- end }}
  labels:
    app: {{ .Values.appLabel }}
  name: {{ .Values.global.armoKubescapeServiceAccountName }}
  namespace: {{ .Values.armoNameSpace }}
automountServiceAccountToken: false
{{- end -}}
