apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.global.beConfig }}
    tier: {{ .Values.global.namespaceTier }}
  name: registry-scan-cronjob-template
data:
  cronjobTemplate: |-
    {{ tpl (.Files.Get "assets/armo-registry-scan-cronjob-ful.yaml") . }}
