{{ template "account_guid" . }}
{{ template "cluster_name" . }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.global.beConfig }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.global.beConfig }}
    tier: {{ .Values.global.namespaceTier }}
data:
  clusterData: |
    {
      "gatewayWebsocketURL": "{{ .Values.armoNotificationService.name }}:{{ .Values.armoNotificationService.websocketService.port }}",
      "gatewayRestURL": "{{ .Values.armoNotificationService.name }}:{{ .Values.armoNotificationService.httpService.port }}",
      "vulnScanURL": "{{ .Values.armoVulnScanner.name }}:{{ .Values.armoVulnScanner.service.port }}",
      "kubevulnURL": "{{ .Values.armoVulnScanner.name }}:{{ .Values.armoVulnScanner.service.port }}",
      "kubescapeURL": "{{ .Values.armoKubescape.name }}:{{ .Values.armoKubescape.service.port }}",
      "triggerNewImageScan": "{{ .Values.armoTriggerNewImageScan }}",
      "accountID": "{{ .Values.accountGuid }}",
      "clusterName": "{{ regexReplaceAll "\\W+" .Values.clusterName "-" | lower }}",
{{- if eq .Values.environment "dev" }} 
      "backendOpenAPI": "{{ .Values.devBackendOpenAPI }}",
      "eventReceiverRestURL": "{{ .Values.devEventReceiverHttpUrl }}",
      "eventReceiverWebsocketURL": "{{ .Values.devK8sReportUrl }}",
      "rootGatewayURL": "wss://{{ .Values.devGateway }}/v1/waitfornotification"
{{- else if eq .Values.environment "staging" }}
      "backendOpenAPI": "{{ .Values.stagingBackendOpenAPI }}",
      "eventReceiverRestURL": "{{ .Values.stagingEventReceiverHttpUrl }}",
      "eventReceiverWebsocketURL": "{{ .Values.stagingK8sReportUrl }}",
      "rootGatewayURL": "wss://{{ .Values.stagingGateway }}/v1/waitfornotification"
{{- else }} 
      "backendOpenAPI": "{{ .Values.backendOpenAPI }}",
      "eventReceiverRestURL": "{{ .Values.eventReceiverHttpUrl }}",
      "eventReceiverWebsocketURL": "{{ .Values.k8sReportUrl }}",
      "rootGatewayURL": "wss://{{ .Values.gateway }}/v1/waitfornotification"
{{- end }}       
    }