kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.armoKubescapeServiceAccountName }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.global.armoKubescapeServiceAccountName }}-roles
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.armoKubescapeServiceAccountName }}
  namespace: {{ .Values.armoNameSpace }}