{{- if and .Values.armoKubescapeScanScheduler.enabled .Values.armoKubescape.enabled .Values.armoKubescape.submit }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.armoKubescapeScanScheduler.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoKubescapeScanScheduler.name }}
    tier: {{ .Values.global.namespaceTier }}
data:
  request-body.json: |-
    {"commands":[{"CommandName":"kubescapeScan","args":{"scanV1": {}}}]}
{{- end }}