{{- if and .Values.armoWebsocket.enabled .Values.armoKubescape.submit }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.armoWebsocket.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoWebsocket.name }}
spec:
  type: {{ .Values.armoWebsocket.service.type }}
  ports:
    - port: {{ .Values.armoWebsocket.service.port }}
      targetPort: {{ .Values.armoWebsocket.service.targetPort }}
      protocol: {{ .Values.armoWebsocket.service.protocol }}
  selector:
    app: {{ .Values.armoWebsocket.name }}
{{- end }}