{{- if and .Values.armoVulnScanner.enabled .Values.armoKubescape.submit }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: vulnscan-cronjob-template
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.global.beConfig }}
    tier: {{ .Values.global.namespaceTier }}
data:
  cronjobTemplate: |-
    {{ tpl (.Files.Get "assets/armo-vulnscan-cronjob-full.yaml") . }}
{{- end }}
