kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.armoServiceAccountName }}-role-binding
  namespace: {{ .Values.armoNameSpace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.global.armoServiceAccountName }}-roles
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.armoServiceAccountName }}
  namespace: {{ .Values.armoNameSpace }}