{{- if and .Values.armoNotificationService.enabled .Values.armoKubescape.submit }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.armoNotificationService.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoNotificationService.name }}
    tier: {{ .Values.global.namespaceTier}}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.armoNotificationService.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.armoNotificationService.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.armoNotificationService.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        tier: {{ .Values.global.namespaceTier}}
        app: {{ .Values.armoNotificationService.name }}
      {{- if .Values.addRevisionLabel }}
        helm.sh/revision: "{{ .Release.Revision }}"
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ toYaml .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Values.armoNotificationService.name }}
          image: "{{ .Values.armoNotificationService.image.repository }}:{{ .Values.armoNotificationService.image.tag }}"
          imagePullPolicy: {{ .Values.armoNotificationService.image.pullPolicy }}
          ports:
            - name: "websocket"
              containerPort: {{ .Values.armoNotificationService.websocketService.port }}
              protocol: TCP
            - name: "rest-api"
              containerPort: {{ .Values.armoNotificationService.httpService.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.armoNotificationService.resources | indent 12 }}
          env:
            - name: WEBSOCKET_PORT
              value: "{{ .Values.armoNotificationService.websocketService.port }}"
            - name: HTTP_PORT
              value: "{{ .Values.armoNotificationService.httpService.port }}"
            {{- range .Values.armoNotificationService.env }}
            - name: {{ .name  }}
              value: "{{ .value }}"
            {{- end }}
          args:
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
          - name: {{ .Values.global.beConfig }}
            mountPath: /etc/config
            readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 10 }}
{{- end }}
{{- if .Values.armoNotificationService.volumeMounts }}
{{ toYaml .Values.armoNotificationService.volumeMounts | indent 10 }}
{{- end }}
      volumes:
        - name: {{ .Values.global.beConfig }}
          configMap:
            name: {{ .Values.global.beConfig }}
            items:
            - key: "clusterData"
              path: "clusterData.json"
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
{{- end }}
{{- if .Values.armoNotificationService.volumes }}
{{ toYaml .Values.armoNotificationService.volumes | indent 8 }}
{{- end }}
      automountServiceAccountToken: false
      {{- with .Values.armoNotificationService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.armoNotificationService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
