{{- if and .Values.armoVulnScanScheduler.enabled .Values.armoKubescape.submit }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.armoVulnScanScheduler.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoVulnScanScheduler.name }}
    tier: {{ .Values.global.namespaceTier }}
data:
  request-body.json: |-
    {"commands":[{"commandName":"scan","designators":[{"designatorType":"Attributes","attributes":{}}]}]}
{{- end }}