kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.kubescapeServiceAccountName }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.global.kubescapeServiceAccountName }}-roles
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.kubescapeServiceAccountName }}
  namespace: {{ .Values.ksNamespace }}