{{- if and .Values.kontroller.enabled .Values.kubescape.submit }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kontroller.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.kontroller.name }}
spec:
  type: {{ .Values.kontroller.service.type }}
  ports:
    - port: {{ .Values.kontroller.service.port }}
      targetPort: {{ .Values.kontroller.service.targetPort }}
      protocol: {{ .Values.kontroller.service.protocol }}
  selector:
    app: {{ .Values.kontroller.name }}
{{- end }}