{{ template "cluster_name" . }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.armoKubescape.name }}-config
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoKubescape.name }}-config
    tier: {{ .Values.global.namespaceTier }}  
data:
  clusterName: {{ regexReplaceAll "\\W+" .Values.clusterName "-" | lower  }}  # deprecate
  customerGUID: {{ template "account_guid" $ }}
  config.json: |
    {
      "customerGUID": {{ template "account_guid" $ }},
      "accountID": {{ template "account_guid" $ }},
      "clusterName": "{{ regexReplaceAll "\\W+" .Values.clusterName "-" | lower  }}"
      "clientID": "{{ .Values.clientID }}",
      "secretKey": "{{ .Values.secretKey }}"
    }