{{- if and .Values.kubevulnScheduler.enabled .Values.kubescape.submit }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.kubevulnScheduler.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.kubevulnScheduler.name }}
    tier: {{ .Values.global.namespaceTier }}
data:
  request-body.json: |-
    {"commands":[{"commandName":"scan","designators":[{"designatorType":"Attributes","attributes":{}}]}]}
{{- end }}