{{- if and .Values.armoVulnScanner.enabled .Values.armoKubescape.submit }}
{{ template "account_guid" . }}
{{ template "cluster_name" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.armoVulnScanner.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoVulnScanner.name }}
    tier: {{ .Values.global.namespaceTier}}
spec:
  replicas: {{ .Values.armoVulnScanner.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.armoVulnScanner.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.armoVulnScanner.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        tier: {{ .Values.global.namespaceTier}}
        app: {{ .Values.armoVulnScanner.name }}
      {{- if .Values.addRevisionLabel }}
        helm.sh/revision: "{{ .Release.Revision }}"
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ toYaml .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Values.armoVulnScanner.name }}
          image: "{{ .Values.armoVulnScanner.image.repository }}:{{ .Values.armoVulnScanner.image.tag }}"
          imagePullPolicy: {{ .Values.armoVulnScanner.image.pullPolicy }}
          ports:
          - name: "vuln-scan-port"
            containerPort: 8080
            protocol: TCP
          - name: "readiness-port"
            containerPort: 8000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: readiness-port
          resources:
{{ toYaml .Values.armoVulnScanner.resources | indent 12 }}
          env:
            - name: PRINT_POST_JSON
              value: "{{ .Values.armoVulnScanner.verbose }}"
            {{- range .Values.armoVulnScanner.env }}
            - name: {{ .name  }}
              value: "{{ .value }}"
            {{- end }}
          args:
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: {{ .Values.global.beConfig }}
              mountPath: /etc/config
              readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
{{- if .Values.armoVulnScanner.volumeMounts }}
{{ toYaml .Values.armoVulnScanner.volumeMounts | indent 12 }}
{{- end }}
      volumes:
        - name: {{ .Values.global.beConfig }}
          configMap:
            name: {{ .Values.global.beConfig }}
            items:
            - key: "clusterData"
              path: "clusterData.json"
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
{{- end }}
{{- if .Values.armoVulnScanner.volumes }}
{{ toYaml .Values.armoVulnScanner.volumes | indent 8 }}
{{- end }}
      serviceAccountName: {{ .Values.global.armoServiceAccountName }}
      automountServiceAccountToken: true
      {{- with .Values.armoVulnScanner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.armoVulnScanner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
