{{- if and .Values.armoCollector.enabled .Values.armoKubescape.submit }}
{{ template "account_guid" . }}
{{ template "cluster_name" . }}
apiVersion: apps/v1
# statefulset is needed in order to avoid two pods reporting from the same cluster in parallel.
# parallel reporting will cause Kubescape SaaS to miss identify the cluster liveness status
kind: StatefulSet
metadata:
  name: {{ .Values.armoCollector.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoCollector.name }}
    tier: {{ .Values.global.namespaceTier}}
spec:
  serviceName: ""
  replicas: {{ .Values.armoCollector.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.armoCollector.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.armoCollector.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: {{ .Values.global.namespaceTier}}
        app: {{ .Values.armoCollector.name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      {{- if .Values.addRevisionLabel }}
        helm.sh/revision: "{{ .Release.Revision }}"
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ toYaml .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
      - image: quay.io/armosec/kubectl:1.24 # https://github.com/armosec/bitnami-docker-kubectl
        name: remove-old-deployments
        command: 
        - bash
        args:
        - -c
        - set -xv; kubectl delete deployment armo-collector -n armo-system; dep_exist=$?; echo $dep_exist; while [ $dep_exist -eq 0 ]; do kubectl get deployment armo-collector -n armo-system; dep_exist=$?; echo $dep_exist; done 
        resources:
          limits:
            cpu: 20m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 40Mi
      containers:
        - name: {{ .Values.armoCollector.name }}
          image: "{{ .Values.armoCollector.image.repository }}:{{ .Values.armoCollector.image.tag }}"
          imagePullPolicy: {{ .Values.armoCollector.image.pullPolicy }}
          ports:
            - name: "readiness-port"
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: readiness-port
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
{{ toYaml .Values.armoCollector.resources | indent 12 }}
          env:
            - name: ACTIVATE_CVE_SCAN_ON_NEW_IMAGE_FEATURE
              value: "{{ .Values.triggerNewImageScan }}"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- range .Values.armoCollector.env }}
            - name: {{ .name  }}
              value: "{{ .value }}"
            {{- end }}
          args:
          - -alsologtostderr
          - -v=4
          - 2>&1
          volumeMounts:
            - name: {{ .Values.global.beConfig }}
              mountPath: /etc/config
              readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
{{- if .Values.armoCollector.volumeMounts }}
{{ toYaml .Values.armoCollector.volumeMounts | indent 12 }}
{{- end }}
      volumes:
        - name: {{ .Values.global.beConfig }}
          configMap:
            name: {{ .Values.global.beConfig }}
            items:
            - key: "clusterData"
              path: "clusterData.json"
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
{{- end }}
{{- if .Values.armoCollector.volumes }}
{{ toYaml .Values.armoCollector.volumes | indent 8 }}
{{- end }}
      serviceAccountName: {{ .Values.global.armoServiceAccountName }}
      automountServiceAccountToken: true
      {{- with .Values.armoCollector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.armoCollector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
