apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.global.armoServiceAccountName }}-roles
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.appLabel }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list", "describe"]